spring.application.name=taskflow
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskflow_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
jwt.secret=17910f2c1588fefef9385166b784240d7302f8c96919b92cb3c9ab42e0839d69
jwt.access.expiration=900000
jwt.refresh.expiration=604800000